apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hugaub2te-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hugaub2te-nodejs 
  name: hugaub2te-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hugaub2te-nodejs 
